name: Provision VM

# on:
#   pull_request:
#     paths:
#       - 'requests/*.yml'

#   push:
#     branches:
#       - main
#     paths:
#       - 'requests/*.yml'


on:
  workflow_dispatch:


jobs:

  validate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5

      - run: pip install pyyaml

      - run: |
              echo "Build artifacts PSS"
              pwd
              ls -la

      - run: python platform/validator/validator.py requests/environment.yaml catalog/sizes.yml catalog/templates.yml

      - uses: actions/upload-artifact@v4
        with:
          name: tfvars
          path: requests/terraform.tfvars.json

  terraform:
    needs: validate

    runs-on: self-hosted

    steps:

      - uses: actions/checkout@v4

      - uses: actions/download-artifact@v4
        with:
          name: tfvars
      
      - name: Copy tfvars
        run: |
          cp terraform.tfvars.json terraform/environments/dev/
          ls -la terraform/environments/dev/

      - name: Terraform Init
        working-directory: terraform/environments/dev
        run: terraform init

      - name: Terraform Plan
        working-directory: terraform/environments/dev
        run: terraform plan -var-file=terraform.tfvars.json

      - name: Terraform Apply
        working-directory: terraform/environments/dev
        run: terraform apply -auto-approve -var-file=terraform.tfvars.json
