name: Provision VM

# on:
#   pull_request:
#     paths:
#       - 'requests/*.yml'

#   push:
#     branches:
#       - main
#     paths:
#       - 'requests/*.yml'


on:
  workflow_dispatch:


jobs:

  validate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5

      - run: pip install pyyaml

      - run: |
              echo "Build artifacts PSS"
              pwd
              ls -la

      - run: python platform/validator/validator.py requests/environment.yaml catalog/sizes.yml

      - uses: actions/upload-artifact@v4
        with:
          name: tfvars
          path: requests/terraform.tfvars.json

  terraform:
    needs: validate

    runs-on: self-hosted

    steps:

      - uses: actions/checkout@v4

      - uses: actions/download-artifact@v4
        with:
          name: tfvars

      - run: terraform init

      - run: terraform plan -var-file=terraform.tfvars.json

    #   - run: terraform apply -auto-approve -var-file=terraform.tfvars.json