name: Order VM

# on:
#   pull_request:
#     paths:
#       - 'requests/*.yml'

#   push:
#     branches:
#       - main
#     paths:
#       - 'requests/*.yml'


on:
  workflow_dispatch:


jobs:

  validate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5

      - run: pip install pyyaml

      - run: python platform/validator/validator.py requests/environment.yaml catalog/sizes.yml catalog/templates.yml

      - uses: actions/upload-artifact@v4
        with:
          name: tfvars
          path: requests/terraform.tfvars.json

  terraform:
    needs: validate

    runs-on: self-hosted

    steps:

      - uses: actions/checkout@v4

      - uses: actions/download-artifact@v4
        with:
          name: tfvars
      
      - name: Copy tfvars
        run: |
          cp terraform.tfvars.json terraform/environments/dev/

      - name: Terraform Init
        working-directory: terraform/environments/dev
        run: terraform init

      - name: Terraform Plan
        working-directory: terraform/environments/dev
        run: terraform plan -var-file=terraform.tfvars.json

      - name: Terraform Apply
        working-directory: terraform/environments/dev
        run: terraform apply -auto-approve -var-file=terraform.tfvars.json
      
      - name: Terraform Output
        working-directory: terraform/environments/dev
        run: terraform output
        
      - name: Get outputs
        working-directory: terraform/environments/dev
        run: terraform output -json > terraform-output.json
      
      - uses: actions/upload-artifact@v4
        with:
          name: terraform-output
          path: terraform/environments/dev/terraform-output.json

  notify:
    needs: terraform

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5

      - uses: actions/download-artifact@v4
        with:
          name: terraform-output
      
      - name: Copy terraform-output
        run: |
          cp terraform-output.json platform/notifier/

      - run: python platform/notifier/notify.py platform/notifier/terraform-output.json

